# Generated by Django 4.1.4 on 2022-12-14 23:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuff_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thing',
            new_name='Stuff',
        ),
    ]
